version: '3.5'
services:
  app:
    image: bakudankun/crowi:latest
    environment:
      MONGO_URI: mongodb://db:27017/crowi
      REDIS_URL: redis://redis:6379/crowi
      PASSWORD_SEED: ${PASSWORD_SEED}
    ports:
    - published: ${LISTEN_PORT}
      target: 3000
      protocol: tcp
      mode: ingress
    volumes:
    - app-uploads-volume:/usr/src/app/public/uploads:rw
    depends_on:
    - db
    networks:
    - network
  db:
    image: mongo:3.6.13
    volumes:
    - db-volume:/data/db:rw
    networks:
    - network
  redis:
    image: redis:alpine
    networks:
    - network
networks:
  network: {}
volumes:
  app-uploads-volume: {}
  db-volume: {}
